//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energeniaal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Energeniaal.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliance.
        /// </summary>
        internal static string Appliance {
            get {
                return ResourceManager.GetString("Appliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliance names.
        /// </summary>
        internal static string ApplianceNames {
            get {
                return ResourceManager.GetString("ApplianceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances.
        /// </summary>
        internal static string Appliances {
            get {
                return ResourceManager.GetString("Appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averages.
        /// </summary>
        internal static string Averages {
            get {
                return ResourceManager.GetString("Averages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all history data from the database?.
        /// </summary>
        internal static string ConfirmDatabaseWipe {
            get {
                return ResourceManager.GetString("ConfirmDatabaseWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to import this data and overwrite existing data?.
        /// </summary>
        internal static string ConfirmImport {
            get {
                return ResourceManager.GetString("ConfirmImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string ConnectMenu {
            get {
                return ResourceManager.GetString("ConnectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily history.
        /// </summary>
        internal static string DailyHistory {
            get {
                return ResourceManager.GetString("DailyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database contains incorrect history data. Please delete all history data and download from the device again, or import from a file..
        /// </summary>
        internal static string DatabaseIncorrect {
            get {
                return ResourceManager.GetString("DatabaseIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayHistory.
        /// </summary>
        internal static string DayHistoryFilename {
            get {
                return ResourceManager.GetString("DayHistoryFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily history.
        /// </summary>
        internal static string DayRadioButton {
            get {
                return ResourceManager.GetString("DayRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all history data.
        /// </summary>
        internal static string DeleteAllHistoryData {
            get {
                return ResourceManager.GetString("DeleteAllHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disconnect.
        /// </summary>
        internal static string DisconnectMenuItem {
            get {
                return ResourceManager.GetString("DisconnectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time;Appliance;kWh;SensorID.
        /// </summary>
        internal static string ExportColumnHeaders {
            get {
                return ResourceManager.GetString("ExportColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year;Appliance;kWh;SensorID.
        /// </summary>
        internal static string ExportColumnHeadersYear {
            get {
                return ResourceManager.GetString("ExportColumnHeadersYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string ExportMenu {
            get {
                return ResourceManager.GetString("ExportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical data.
        /// </summary>
        internal static string HistoricalData {
            get {
                return ResourceManager.GetString("HistoricalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file has unexpected format. Expected:.
        /// </summary>
        internal static string ImportFileUnexpectedFormat {
            get {
                return ResourceManager.GetString("ImportFileUnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching language....
        /// </summary>
        internal static string LanguageChangeWaitText {
            get {
                return ResourceManager.GetString("LanguageChangeWaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile.
        /// </summary>
        internal static string Logfile {
            get {
                return ResourceManager.GetString("Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthHistory.
        /// </summary>
        internal static string MonthHistoryFilename {
            get {
                return ResourceManager.GetString("MonthHistoryFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month history.
        /// </summary>
        internal static string MonthHistoryMenuItem {
            get {
                return ResourceManager.GetString("MonthHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month history.
        /// </summary>
        internal static string MonthHistoryRadioButton {
            get {
                return ResourceManager.GetString("MonthHistoryRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for appliance.
        /// </summary>
        internal static string NoDataForAppliance {
            get {
                return ResourceManager.GetString("NoDataForAppliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for appliance/phase.
        /// </summary>
        internal static string NoDataForApplianceAndPhase {
            get {
                return ResourceManager.GetString("NoDataForApplianceAndPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per day of week.
        /// </summary>
        internal static string PerDayOfWeekRadioButton {
            get {
                return ResourceManager.GetString("PerDayOfWeekRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per time of day.
        /// </summary>
        internal static string PerTimeOfDayRadioButton {
            get {
                return ResourceManager.GetString("PerTimeOfDayRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        internal static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\lang9\b\f0\fs19 Release Notes\b0\par
        ///The Energeniaal application reads both real-time and historical data from the Current Cost EnviR Display Unit. The real-time data includes current time, temperature, and energy usage. \par
        ///The Current Cost Display outputs three types of histori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReleaseNotesRtf {
            get {
                return ResourceManager.GetString("ReleaseNotesRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliance.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoHourHistory.
        /// </summary>
        internal static string TwoHourHistoryFilename {
            get {
                return ResourceManager.GetString("TwoHourHistoryFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-hour history.
        /// </summary>
        internal static string TwoHourHistoryMenuItem {
            get {
                return ResourceManager.GetString("TwoHourHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-hour history.
        /// </summary>
        internal static string TwoHourHistoryRadioButton {
            get {
                return ResourceManager.GetString("TwoHourHistoryRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Energeniaal website.
        /// </summary>
        internal static string VisitEnergeniaalWebsite {
            get {
                return ResourceManager.GetString("VisitEnergeniaalWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole house.
        /// </summary>
        internal static string WholeHouseSensor {
            get {
                return ResourceManager.GetString("WholeHouseSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History data deleted..
        /// </summary>
        internal static string WipeConfirmation {
            get {
                return ResourceManager.GetString("WipeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t detect COM ports. Please select port from Connect menu..
        /// </summary>
        internal static string WMIError {
            get {
                return ResourceManager.GetString("WMIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YearHistory.
        /// </summary>
        internal static string YearHistoryFilename {
            get {
                return ResourceManager.GetString("YearHistoryFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year history.
        /// </summary>
        internal static string YearHistoryMenuItem {
            get {
                return ResourceManager.GetString("YearHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year history.
        /// </summary>
        internal static string YearHistoryRadioButton {
            get {
                return ResourceManager.GetString("YearHistoryRadioButton", resourceCulture);
            }
        }
    }
}
